# Site settings
title: Versity
email: versitylan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Versity. L'évènement LAN à Cergy.
baseurl: "/misc/versity" # the subpath of your site, e.g. /blog/
url: "http://uinelj.eu" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
